#!/bin/bash -l
#PBS -A DBIC
#PBS -q default
#PBS -N forward

#PBS -M heejung.jung.gr@dartmouth.edu
#PBS -m ea

#PBS -l nodes=1:ppn=16

#PBS -l walltime=24:00:00

cd $PBS_O_WORKDIR


module load python/2.7-Anaconda  
source /optnfs/common/miniconda3/etc/profile.d/conda.sh
conda activate haxby_mvpc
python /dartfs/rc/lab/D/DBIC/DBIC/f0042x1/life-encoding/scripts/s03_ridge-regression/c03_ridge_regression.py ${MODEL} ${ALIGN} ${STIM} ${RUN} ${HEMI}
